# Generated by Django 4.2.6 on 2023-10-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_service_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Bodyweight Cardio', 'Bodyweight Cardio'), ('Bodyweight Core', 'Bodyweight Core'), ('Beginner HIIT', 'Beginner HIIT'), ('Total Body Strength', 'Total Body Strength')], default='Group Classes', max_length=50),
        ),
    ]
